name: Lint
on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install deps
      run: |
        pip install poetry
        poetry install --no-dev

    - name: Install flake8 outside poetry env
      run: pip install flake8

    - name: Lint with flake8
      run: "flake8 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s'"
